- name: apt update
  become: true
  shell: apt update
- name: apt upgrade
  become: true
  shell: apt upgrade -y
- name: software install by apt
  become: true
  shell: apt install -y language-pack-ja \
    screen \
    tig \
    ruby \
    ruby-dev \
    libffi-dev \
    python-pip \
    golang \
    php7.2 \
    php7.2-common \
    php7.2-cli \
    php7.2-fpm \
    php7.2-mysql \
    php7.2-dev \
    php7.2-mbstring \
    php7.2-zip
- name: get composer
  get_url: url=https://getcomposer.org/installer dest=$HOME/installer
- name: software install by php
  shell: cd $HOME \
    && php installer \
    && rm installer \
    && sudo mv composer.phar /usr/local/bin/composer \
    && sudo chmod +x /usr/local/bin/composer
- name: software install by pip
  become: true
  shell: pip install cffi docker-compose
- name: software install by gem
  become: true
  shell: gem install sass
- name: cleaning
  become: true
  shell: apt autoremove -y
