- name: make bash setting directory
  file: path=$HOME/.bash state=directory
- name: link bash setting
  file: src={{ ansible_env.PWD }}/files/my_extend dest=$HOME/.bash/my_extend state=link
- name: add bash setting
  shell: cat {{ ansible_env.PWD }}/bash/.bash_extend >> $HOME/.bashrc
